# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 280347882be4b540c9c322734060f92f1c68e4b542819cad5b1eb4627426d2284953643f41c810b66f09c0525d37a632962eb7065270fc504c2b9a13a73a2dea

test:
  secret_key_base: fa8a864a5b33e4270b3cd09903b846cea4634e64429acb4b879afd175f8e6ff0543d1af79ee9bdb38932d169ff5acf9fc0662a2d98de0237f1e3bf2de2b57b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
